"""Canonical field definitions for Silver/Gold project tables."""

from __future__ import annotations

CANONICAL_COLUMNS: list[str] = [
    "project_key",
    "source_project_id",
    "source_name",
    "observation_date",
    "published_at",
    "queue_date",
    "status",
    "status_raw",
    "status_clean",
    "withdrawal_date",
    "completion_date",
    "operational_date",
    "proposed_service_date",
    "capacity_mw",
    "summer_capacity_mw",
    "winter_capacity_mw",
    "storage_power_mw",
    "storage_duration_hours",
    "technology_primary",
    "technology_secondary",
    "is_hybrid",
    "technology_count",
    "technology_raw",
    "solar_mw",
    "wind_mw",
    "battery_mw",
    "gas_mw",
    "service_type",
    "state",
    "state_code",
    "county_name",
    "county_name_clean",
    "county_fips",
    "latitude",
    "longitude",
    "poi_name",
    "poi_name_clean",
    "poi_key",
    "transmission_owner",
    "transmission_owner_clean",
    "study_cycle",
    "study_group",
    "study_phase",
    "post_gia_status",
    "dp1_eris_mw",
    "dp1_nris_mw",
    "dp2_eris_mw",
    "dp2_nris_mw",
    "source_file",
    "source_id",
    "quality_score",
    # date precision / parse flags (attached to primary dates via sidecar columns)
    "queue_date_precision",
    "queue_date_parse_error",
    "withdrawal_date_precision",
    "withdrawal_date_parse_error",
    "completion_date_precision",
    "completion_date_parse_error",
    "operational_date_precision",
    "operational_date_parse_error",
    "proposed_service_date_precision",
    "proposed_service_date_parse_error",
    # capacity flags
    "capacity_negative",
    "capacity_zero",
    "capacity_extreme",
    "component_capacity_conflict",
    "status_consistency_flag",
]

STRING_ID_COLUMNS = [
    "project_key",
    "source_project_id",
    "study_cycle",
    "study_group",
    "county_fips",
    "poi_key",
]

DATE_COLUMNS = [
    "observation_date",
    "published_at",
    "queue_date",
    "withdrawal_date",
    "completion_date",
    "operational_date",
    "proposed_service_date",
]

NUMERIC_MW_COLUMNS = [
    "capacity_mw",
    "summer_capacity_mw",
    "winter_capacity_mw",
    "storage_power_mw",
    "storage_duration_hours",
    "solar_mw",
    "wind_mw",
    "battery_mw",
    "gas_mw",
    "dp1_eris_mw",
    "dp1_nris_mw",
    "dp2_eris_mw",
    "dp2_nris_mw",
]

# Snapshot natural key
SNAPSHOT_NATURAL_KEY = ["project_key", "observation_date", "source_name"]

# Columns that must never be used as features (outcomes / labels)
OUTCOME_COLUMNS = [
    "withdraw_next_12m",
    "next_outcome",
    "complete_followup",
    "withdrawal_event",
    "operation_event",
    "outcome_type",
    "outcome_date",
]

MASTER_COLUMNS = [
    "project_key",
    "queue_date",
    "technology_primary",
    "technology_secondary",
    "state",
    "state_code",
    "county_fips",
    "poi_key",
    "first_observed_date",
    "last_observed_date",
]

SNAPSHOT_CORE_COLUMNS = [
    "project_key",
    "observation_date",
    "published_at",
    "source_name",
    "source_id",
    "status",
    "status_raw",
    "status_clean",
    "capacity_mw",
    "proposed_service_date",
    "study_phase",
    "study_group",
    "study_cycle",
    "service_type",
    "post_gia_status",
    "quality_score",
    "queue_date",
    "withdrawal_date",
    "completion_date",
    "operational_date",
    "technology_primary",
    "technology_secondary",
    "is_hybrid",
    "state",
    "state_code",
    "county_fips",
    "poi_key",
    "poi_name",
    "summer_capacity_mw",
    "winter_capacity_mw",
    "source_project_id",
    "source_file",
]
